# Generated by Django 6.0.2 on 2026-03-02 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_system', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecommendation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_system.recommendationmodel'),
        ),
        migrations.AddField(
            model_name='recommendedbook',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='core_system.userrecommendation'),
        ),
    ]
